/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectstackVer2;
import projectstack.*;
import javax.swing.*;
import java.awt.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JPanel;
import javax.swing.table.JTableHeader;

import java.util.Stack;

public class Create2 extends javax.swing.JFrame {
    DefaultTableModel model1, model2, model3;
    
    int size = 1;
    int MAXSTK1, ITEM;
    Stack<Integer> STACK1 = new Stack<>();
    int TOP2 = -1, MAXSTK2;
    Stack<Integer> STACK2 = new Stack<>();
    int TOP3 = -1, MAXSTK3;
    Stack<Integer> STACK3 = new Stack<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Create2.class.getName());
    
       /*----------------------
    public  void PUSH(int item) {
        if (TOP1 == MAXSTK1-1) {
            System.out.println("OVERFLOW");
        } else {
          TOP1++;     
           STACK1[TOP1] = item;
        System.out.println("PUSH :" + item + "  OK.");
  //      jTable1.setValueAt(STACK[TOP], (9-TOP), 0);
        }
    }
//------------------------------------
    public  void POP(){
    if(TOP1==-1)
           System.out.println("UNDERFLOW");
       
     else
    {
       ITEM=STACK1[TOP1];
       --TOP1;
    }
    System.out.println("Pop Data: "+ITEM);
 }*/
    public  void showDatainStack() {
        System.out.println();
        System.out.print("Stack1:");
     //   for (int i = 0; i <= TOP; i++){ jTable1.setValueAt("", (9-TOP), 0); }
        for (int i = 0; i <= STACK1.size()-1; i++) {
            System.out.print(STACK1.get(i) + ",");
            jTable1.setValueAt(STACK1.get(i), ((STACK1.size()-1)-i), 0);
        }
    }
 public  void clearDatainStack(int TOP) {       
        for (int i = 0; i <= (TOP+1); i++) {
            jTable1.setValueAt("", ((size-1)-i), 0);
        }
    }
    
        public  void showDatainStack2() {
        System.out.println();
        System.out.print("Stack2:");
     //   for (int i = 0; i <= TOP; i++){ jTable1.setValueAt("", (9-TOP), 0); }
        for (int i = 0; i <= STACK2.size()-1; i++) {
            System.out.print(STACK2.get(i) + ",");
            jTable2.setValueAt(STACK2.get(i), ((STACK2.size()-1)-i), 0);
        }
    }
         public  void showDatainStack3() {
        System.out.println();
        System.out.print("Stack3:");
     //   for (int i = 0; i <= TOP; i++){ jTable1.setValueAt("", (9-TOP), 0); }
        for (int i = 0; i <= STACK3.size()-1; i++) {
            System.out.print(STACK3.get(i) + ",");
            jTable3.setValueAt(STACK3.get(i), ((STACK3.size()-1)-i), 0);
        }
    }
         
    public Create2() {
        initComponents();
        model1 = new DefaultTableModel(new Object[]{"STACK1"}, 0);
                 jTable1.setModel(model1);
                  model2 = new DefaultTableModel(new Object[]{"STACK2"}, 0);
                 jTable2.setModel(model2);
                  model3 = new DefaultTableModel(new Object[]{"STACK3"}, 0);
                 jTable3.setModel(model3);
         this.getContentPane().setBackground(new Color(98, 149, 150));
        jTable1.setRowHeight(30);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable1.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));
        
        jTable2.setRowHeight(30);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable2.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));

        jTable3.setRowHeight(30);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(200);
        jTable3.setFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 18));
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER); // แนวนอน
        centerRenderer.setVerticalAlignment(SwingConstants.CENTER);   // แนวตั้ง
        
        jPanel1.setBorder(BorderFactory.createLineBorder(new Color(200,200,200), 2, true));
        jTable1.setBackground(new Color(255, 192, 203));
        jTable2.setBackground(new Color(173, 253, 162));    
        jTable3.setBackground(new Color(177, 252, 250));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                Graphics2D g2d = (Graphics2D) g;
                int width = getWidth();
                int height = getHeight();

                // ไล่สีจากบนลงล่าง
                Color color1 = new Color(60, 90, 91);
                Color color2 = new Color(186, 208, 209);
                GradientPaint gp = new GradientPaint(0, 0, color1, 0, height, color2);
                g2d.setPaint(gp);
                g2d.fillRect(0, 0, width, height);
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 153, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable3.setForeground(new java.awt.Color(0, 153, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jLabel1.setText("TOP1 = -");

        jLabel3.setText("TOP2 = -");

        jLabel4.setText("TOP3 = -");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MAXSTACK = ");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAXSTACK = ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("MAXSTACK = ");

        jButton4.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton5.setText(">>");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton6.setText("<");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton7.setText(">");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton8.setText("<<");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton9.setText("<");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                .addGap(90, 90, 90)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(87, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(255, 255, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s1 (3).png"))); // NOI18N

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton2.setText("PUSH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton3.setText("POP");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tekton Pro Ext", 1, 14)); // NOI18N
        jButton1.setText("Build STACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 153));
        jButton10.setFont(new java.awt.Font("Tekton Pro", 1, 18)); // NOI18N
        jButton10.setText("Reverse");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit2 (1).png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(this, "version นี้ท่านไม่ต้อง input ขนาด\nสามารถ push ข้อมูลได้เลยค่ะ");
        System.out.println("You no longer need to input the size of the stack. You can just push elements directly");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String inputStr = JOptionPane.showInputDialog(null, "กรอกตัวเลขเพื่อใส่ค่าลงไป");
        System.out.println("Pls take number push in stack");
        int value = Integer.parseInt(inputStr);
        if(STACK1.size()!=0){
            if(value>=STACK1.get(STACK1.size()-1)){
                System.out.println("Pls input lower number");
                JOptionPane.showMessageDialog(null, "กรุณาใส่เลขที่น้อยลงกว่าเดิม ");
               
                return;
            }
        }
                   
                    model1.addRow(new Object[]{value});
                    model2.addRow(new Object[]{""});
                    model3.addRow(new Object[]{""});
                    
               STACK1.push(value);
        jLabel5.setText("MAXSTACK1 = "+STACK1.size());
        showDatainStack();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(STACK1.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        jTable1.setValueAt("", 0, 0);
        STACK1.pop();
        jLabel5.setText("MAXSTACK = "+STACK1.size());
        //clearDatainStack();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(STACK1.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        int K=STACK1.size();
        int value;
        int row = jTable1.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
            value=STACK1.pop();
            STACK2.push(value);
            jTable1.setValueAt("",row , 0);
            row--;
        }
        showDatainStack2();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        jLabel5.setText("MAXSTACK = "+STACK1.size());
        jLabel6.setText("MAXSTACK = "+STACK2.size());
        System.out.println("Move data from STACK1 to STACK2");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if(STACK1.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        int K=STACK1.size();
        int value;
        int row = jTable1.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
                value=STACK1.pop();
                STACK3.push(value);
                jTable1.setValueAt("",row , 0);
                row--;
        }
        showDatainStack3();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable3.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Move data from STACK1 to STACK3");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(STACK2.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        int K=STACK2.size();
        int value;
        int row = jTable2.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
                value=STACK2.pop();
                STACK1.push(value);
                jTable2.setValueAt("",row , 0);
                row--;
        }
        showDatainStack();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Move data from STACK2 to STACK1");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(STACK2.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        int K=STACK2.size();
        int value;
        int row = jTable2.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
                value=STACK2.pop();
                STACK3.push(value);
                jTable2.setValueAt("",row, 0);
                row--;
        }
        showDatainStack3();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable3.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Move data from STACK2 to STACK3");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(STACK3.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
       int K=STACK3.size();
        int value;
        int row = jTable3.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
                value=STACK3.pop();
                STACK1.push(value);
                jTable3.setValueAt("",row , 0);
                row--;
        }
        showDatainStack();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable1.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Move data from STACK3 to STACK1");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(STACK3.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }
        int K=STACK3.size();
        int value;
        int row = jTable3.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
                value=STACK3.pop();
                STACK2.push(value);
                jTable3.setValueAt("",row , 0);
                row--;
        }
        showDatainStack2();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Move data from STACK3 to STACK2");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(STACK1.isEmpty() && STACK2.isEmpty() && STACK3.isEmpty()){
                System.out.println("Stack empty");
                JOptionPane.showMessageDialog(null, "STACK ว่างค่ะ ");
                return;
        }else if(STACK1.isEmpty()){
                System.out.println("Pls move data come back to STACK1");
                JOptionPane.showMessageDialog(null, "ย้ายข้อมูลกลับมาที่ STACK1 ก่อนค่ะ ");
                return;
        }
        int K=STACK1.size();
        int value;
        int row = jTable1.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
            value=STACK1.pop();
            STACK2.push(value);
            jTable1.setValueAt("", row, 0);
            row--;
        }
        K=STACK2.size();
        row = jTable2.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
            value=STACK2.pop();
            STACK3.push(value);
            jTable2.setValueAt("", row, 0);
            row--;
        }
        K=STACK3.size();
        row = jTable3.getRowCount() - 1;
        for(int i=0;i<=K-1;i++){
            value=STACK3.pop();
            STACK1.push(value);
            jTable3.setValueAt("", row, 0);
            row--;
        }
        showDatainStack();
        showDatainStack2();
        showDatainStack3();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
centerRenderer.setVerticalAlignment(SwingConstants.CENTER);
jTable2.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
System.out.println("Reverse Number");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        Front move = new Front();  // สร้างหน้าฟอร์มใหม่
            move.setVisible(true);     // แสดง Form2
            this.dispose(); 
    }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        UIManager.put("OptionPane.messageFont", new Font("Tahoma", Font.PLAIN, 16));
        UIManager.put("OptionPane.buttonFont", new Font("Tahoma", Font.PLAIN, 16));
        java.awt.EventQueue.invokeLater(() -> new Create2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
